import { SpeedInsights } from "@vercel/speed-insights/next"

import { Toaster } from "@/components/ui/toaster"

import { ThemeProvider } from "@/components/ThemeProvider"
import Navbar from "@/components/Navbar"

import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Tracker",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased md:overflow-y-hidden`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Navbar />

                    <div className="min-h-[100dvh] bg-slate-100 bg-gradient-to-br bg-fixed dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
                        {children}
                    </div>
                    <SpeedInsights />
                </ThemeProvider>
                <Toaster />
            </body>
        </html>
    )
}
